CREATE TABLE EMPLOYEE3(
    EmpId INT  NOT NULL,
    FirstName VARCHAR(200),
    LAstName VARCHAR(200),
    EmpAGE INT,
    CHECK(EmpAGE>20)
);

-- DESC EMPLOYEE3;


-- INSERT INTO EMPLOYEE3 VALUES(1,'Tom','D J',18);
-- check violated
INSERT INTO EMPLOYEE3 VALUES(1,'Tom','D J',21);
SELECT *  FROM EMPLOYEE3;
